name: Generate Snake Animation

# Trigger the workflow daily and allow manual triggers
on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight
  workflow_dispatch:     # Allows manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (if your snake animation script uses Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the snake animation script
      - name: Run Snake Animation
        run: python generate_snake_animation.py

      # Step 5: Commit and push the generated animation
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add animations/  # folder where your animation output is saved
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
